defaults: &defaults
  merchantIdentifier: <%= ENV["border_guru_merchant_identifier"] %>
  key: <%= ENV["border_guru_key"] %>
  secret: <%= ENV["border_guru_secret"] %>
  host: http://demo.borderguru.com/

  ftp:
    local_directory: /public/uploads/border_guru_ftp/
    remote_directory: /files
    host: ftp.borderguru.com
    port: 1348
    username: <%= ENV["border_guru_ftp_username"] %>
    password: <%= ENV["border_guru_ftp_password"] %>

local:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults
  ftp:
    local_directory: /public/uploads/border_guru_test/
    remote_directory: /files
    host: ftp.borderguru.com
    port: 1348
    username: <%= ENV["border_guru_ftp_username"] %>
    password: <%= ENV["border_guru_ftp_password"] %>
    log: borderguru_cron_test.log

staging:
  <<: *defaults

production:
  <<: *defaults
  host: http://app.borderguru.com/
