bad_format:
  code: 1
  error: "Bad format."

bad_credentials:
  code: 2
  error: "Bad credentials."

unknown_id:
  code: 3
  error: "Unknown ID."

wrong_update_attributes:
  code: 4
  error: "Wrong update attributes."

impossible_to_remove:
  code: 5
  error: "Impossible to remove."

resource_not_found:
  code: 6
  error: "Resource not found."

unauthorized_page:
  code: 7
  error: "Unauthorized page access."