defaults: &defaults
  app_cache_expire_limit: 10.minutes
  max_num_tags: 3
  max_num_sales_channels: 12
  max_add_to_cart_each_time: 15
  max_tiny_text_length: 64
  max_short_text_length: 256
  max_medium_text_length: 1000
  max_long_text_length: 2500
  min_password_length: 8

local:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
  app_cache_expire_limit: 1.hours
