production:
  clients:
    default:
      database: a_chat_development
      hosts:
        #- 207.226.141.12:27017
        - 192.168.100.100:27017
      options:
        user: achat
        password: achat2cool
  options:
    use_activesupport_time_zone: true
    raise_not_found_error: false

staging:
  clients:
    default:
      database: a_chat_development # We could login to the production database for real test
      hosts:
        - dogen.mongohq.com:10020
      options:
        user: achat
        password: achat2cool
  options:
    use_activesupport_time_zone: true
    raise_not_found_error: false

development:
  clients:
    default:
      database: digpanda
      hosts:
        - localhost:27017
      options:
        user: loschcode
        password: achat2cool

  options:
    use_activesupport_time_zone: true
    raise_not_found_error: false

test:
  clients:
    default:
      database: a_chat_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_retries: 1
        retry_interval: 0
        use_activesupport_time_zone: true
        #allow_dynamic_fields: true
local:
  clients:
    default:
      database: a_chat_development
      hosts:
        - localhost:27017
      options:
        user: achat
        password: achat2cool

  # Configure Mongoid specific options. (optional)
  options:
    use_activesupport_time_zone: true
    raise_not_found_error: false
