production:
  clients:
    default:
      database: a_chat_development
      hosts:
        #- 207.226.141.12:27017
        - 192.168.100.100:27017
      options:
        user: gitb
        password: lyh2good
  options:
    use_utc: true
    use_activesupport_time_zone: false
    raise_not_found_error: true

staging:
  clients:
    default:
      database: a_chat_development # We could login to the production database for real test
      hosts:
        - dogen.mongohq.com:10020
      options:
        user: gitb
        password: lyh2cool
  options:
    use_utc: true
    use_activesupport_time_zone: false
    raise_not_found_error: true

development:
  clients:
    default:
      database: digpanda
      hosts:
        - localhost:27017
      options:
        user: loschcode
        password: achat2cool

  options:
    use_utc: true
    use_activesupport_time_zone: false
    raise_not_found_error: true

test:
  clients:
    default:
      database: digpanda_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        #user: loschcode
        #password: achat2cool

        max_retries: 1
        retry_interval: 0
        use_utc: true
        use_activesupport_time_zone: false
        #allow_dynamic_fields: true
  options:
    use_utc: true
    use_activesupport_time_zone: false
    raise_not_found_error: true

local:
  clients:
    default:
      database: a_chat_development
      hosts:
        - localhost:27017
      options:
        user: achat
        password: achat2cool

  # Configure Mongoid specific options. (optional)
  options:
    use_utc: true
    use_activesupport_time_zone: false
    raise_not_found_error: true
