development:
  clients:
    default:
      database: a_chat_development
      hosts:
        - dogen.mongohq.com:10020
      options:
        user: achat
        password: achat2cool
  options:
    use_activesupport_time_zone: true
    raise_not_found_error: false

test:
  clients:
    default:
      database: digpanda
      hosts:
        - localhost:27017
      options:
        user: loschcode
        password: pandarocks
        read:
          mode: :primary
        max_retries: 1
        retry_interval: 0
        use_activesupport_time_zone: true
        #allow_dynamic_fields: true

local:
  clients:
    default:
      database: a_chat_development
      hosts:
        - localhost:27017
      options:
        user: achat
        password: achat2cool

  # Configure Mongoid specific options. (optional)
  options:
    use_activesupport_time_zone: true
    raise_not_found_error: false
