production:
  clients:
    default:
      database: a_chat_development
      hosts:
        - 192.168.100.100:27017
      options:
        user: gitb
        password: lyh2good
        server_selection_timeout: 90
      logger: false
  options:
    use_utc: false
    use_activesupport_time_zone: true
    raise_not_found_error: true

preproduction:
  clients:
    default:
      database: a_chat_development # We could login to the production database for real test
      hosts:
        # - dogen.mongohq.com:10020
        - aws-eu-central-1-portal.1.dblayer.com:15202
      options:
        user: gitb
        password: lyh2cool
      logger: false
  options:
    use_utc: false
    use_activesupport_time_zone: true
    raise_not_found_error: true

staging:
  clients:
    default:
      database: a_chat_development # We could login to the production database for real test
      hosts:
        #- dogen.mongohq.com:10020
        - aws-eu-central-1-portal.1.dblayer.com:15202
      options:
        user: gitb
        password: lyh2cool
  options:
    use_utc: false
    use_activesupport_time_zone: true
    raise_not_found_error: true

development:
  clients:
    default:
      database: digpanda
      hosts:
        - localhost:27017
      options:
        user: loschcode
        password: digpanda

  options:
    use_utc: false
    use_activesupport_time_zone: true
    raise_not_found_error: true

test:
  clients:
    default:
      database: digpanda_test<%= ENV['TEST_ENV_NUMBER'] %> # environment variable from `parallel_tests`
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        #user: loschcode
        #password: achat2cool

        max_retries: 1
        retry_interval: 0
        #allow_dynamic_fields: true
  options:
    use_utc: false
    use_activesupport_time_zone: true
    raise_not_found_error: true

local:
  clients:
    default:
      database: a_chat_development
      hosts:
        - localhost:27017
      options:
        user: achat
        password: achat2cool

  # Configure Mongoid specific options. (optional)
  options:
    use_utc: false
    use_activesupport_time_zone: true
    raise_not_found_error: true
