:concurrency:  5
:logfile: log/sidekiq.log
:pidfile: tmp/pids/sidekiq.pid
development:
  :concurrency: 5
staging:
  :concurrency: 10
preproduction:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - default
  - one_at_a_time
:limits:
  one_at_a_time: 1
