defaults: &defaults
  username: <%= ENV["wechat_username"] %>
  password: <%= ENV["wechat_password"] %>
  scope: snsapi_login

local:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  username: <%= ENV["wechat_username"] %>
  password: <%= ENV["wechat_password"] %>
  scope: snsapi_login
