defaults: &defaults
  elastic_api:
    username: engine.digpanda
    password: x3Zyr8MaY7TDxj6F
    engine_url: https://sandbox-engine.thesolution.com/engine/rest/
  merchants:
    reseller_id: nba81H29Gba
    package_id: digpandapaket1
    country: DEU
    signup: https://www.checkoutportal.de/de_DE/signup/
    status:
      - unactive
      - active
      - processing
      - documents_complete
      - declined
      - terminated
  hpp:
    hosted_payment_url: https://sandbox-engine.thesolution.com/engine/hpp/ # http://api-test.wirecard.com/engine/hpp/ # https://sandbox-engine.thesolution.com/engine/hpp/
    default_redirect_url: http://local.dev:3000/orders/checkout_success # https://sandbox-engine.thesolution.com/shop/complete.jsp
    success_redirect_url : http://local.dev:3000/orders/checkout_success
    fail_redirect_path : http://local.dev:3000/orders/checkout_fail
    psp_name: demo
    payment_method: upop
    transaction_type: debit

local:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults
  hpp:
    hosted_payment_url: https://sandbox-engine.thesolution.com/engine/hpp/
    default_redirect_url: https://sandbox-engine.thesolution.com/shop/complete.jsp
    success_redirect_url : https://www.germanyintheboxdev.com/orders/checkout_success
    fail_redirect_path : https://www.germanyintheboxdev.com/orders/checkout_fail
    psp_name: demo
    payment_method: upop
    transaction_type: debit

production:
  <<: *defaults
  elastic_api:
    username: 000000316FF50E1E-EMDigPanda
    password: pdE_cf0SnYAq
    engine_url: http://www.elastic-payments.com/schema/payment
  hpp:
    hosted_payment_url: http://www.elastic-payments.com/schema/payment
    default_redirect_url: http://www.elastic-payments.com/schema/payment/shop/complete.jsp
    success_redirect_url : https://www.germanyinthebox.com/orders/checkout_success
    fail_redirect_path : https://www.germanyinthebox.com/orders/checkout_fail
    psp_name: demo
    payment_method: upop
    transaction_type: debit
