defaults: &defaults

  elastic_api:
    # PROD
    username: 000000316FF50E1E-EMDigPanda
    password: pdE_cf0SnYAq
    engine_url: https://api.wirecard.com/engine/rest/

    # CREDIT CARD :
    # username: 70000-APILUHN-CARD
    # password: 8mhwavKVb91T
    # engine_url: https://api-test.wirecard.com/engine/rest/

    # UNIONPAY :
    # username: engine.digpanda
    # password: x3Zyr8MaY7TDxj6F
    # engine_url: https://sandbox-engine.thesolution.com/engine/rest/

  hpp:

    # CREDITCARD :
    demo: # needed in development and testing only
     ee_maid_cc: 9105bb4f-ae68-4768-9c3b-3eda968f57ea
     ee_secret_cc: d1efed51-4cb9-46a5-ba7b-0fdc87a66544

    hosted_payment_url: https://api-test.wirecard.com/engine/hpp/
    psp_name: wirecard
    default_payment_method: # let empty to make no choice

    # UNION PAY :
    # demo: # needed in development and testing only
    #   ee_maid_cc: dfc3a296-3faf-4a1d-a075-f72f1b67dd2a
    #   ee_secret_cc: 6cbfa34e-91a7-421a-8dde-069fc0f5e0b8
    #
    # hosted_payment_url: https://sandbox-engine.thesolution.com/engine/hpp/
    # psp_name: demo
    # default_payment_method: upop # let empty to make no choice

    # UNIVERSAL
    transaction_types:
      upop: debit
      creditcard: purchase
      default: purchase

    default_redirect_url: http://local.dev:3000/orders/checkout_success
    cancel_redirect_url: http://local.dev:3000/orders/checkout_cancel
    processing_redirect_url: http://local.dev:3000/orders/checkout_processing
    success_redirect_url : http://local.dev:3000/orders/checkout_success
    fail_redirect_url: http://local.dev:3000/orders/checkout_fail

  merchants:
    reseller_id: nba81H29Gba
    package_id: digpandapaket1
    country: DEU
    signup: https://www.checkoutportal.de/de_DE/signup/
    status:
      - unactive
      - active
      - processing
      - documents_complete
      - declined
      - terminated

local:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults

  elastic_api:
    UNIONPAY :
    username: engine.digpanda
    password: x3Zyr8MaY7TDxj6F
    engine_url: https://sandbox-engine.thesolution.com/engine/rest/
  hpp:
    # UNION PAY :
    demo: # needed in development and testing only
      ee_maid_cc: dfc3a296-3faf-4a1d-a075-f72f1b67dd2a
      ee_secret_cc: 6cbfa34e-91a7-421a-8dde-069fc0f5e0b8

      hosted_payment_url: https://sandbox-engine.thesolution.com/engine/hpp/
      psp_name: demo
      default_payment_method: upop # let empty to make no choice
    # UNIVERSAL
    transaction_types:
      upop: debit
      creditcard: purchase
      default: purchase

    default_redirect_url: http://local.dev:3000/orders/checkout_success
    cancel_redirect_url: http://local.dev:3000/orders/checkout_cancel
    processing_redirect_url: http://local.dev:3000/orders/checkout_processing
    success_redirect_url : http://local.dev:3000/orders/checkout_success
    fail_redirect_url: http://local.dev:3000/orders/checkout_fail

staging:
  <<: *defaults
  hpp:

    # CREDITCARD :
    demo: # needed in development and testing only
     ee_maid_cc: 9105bb4f-ae68-4768-9c3b-3eda968f57ea
     ee_secret_cc: d1efed51-4cb9-46a5-ba7b-0fdc87a66544

    hosted_payment_url: https://api-test.wirecard.com/engine/hpp/
    psp_name: wirecard
    default_payment_method: creditcard # let empty to make no choice

    # UNIVERSAL
    transaction_types:
      upop: debit
      creditcard: purchase
      default: purchase

    default_redirect_url: https://www.germanyintheboxdev.com/orders/checkout_success
    cancel_redirect_url: https://www.germanyintheboxdev.com/orders/checkout_cancel
    processing_redirect_url: https://www.germanyintheboxdev.com/orders/checkout_processing
    success_redirect_url : https://www.germanyintheboxdev.com/orders/checkout_success
    fail_redirect_url: https://www.germanyintheboxdev.com/orders/checkout_fail

production:
  <<: *defaults
  elastic_api:
    username: 000000316FF50E1E-EMDigPanda
    password: pdE_cf0SnYAq
    engine_url: https://api.wirecard.com/engine/rest/
  hpp:
    hosted_payment_url: https://api.wirecard.com/engine/hpp/
    psp_name: wirecard
    default_payment_method: # let empty to make no choice

    # UNIVERSAL
    transaction_types:
      upop: debit
      creditcard: purchase
      default: purchase

    default_redirect_url: https://www.germanyinthebox.com/orders/checkout_success
    cancel_redirect_url: https://www.germanyinthebox.com/orders/checkout_cancel
    processing_redirect_url: https://www.germanyinthebox.com/orders/checkout_processing
    success_redirect_url : https://www.germanyinthebox.com/orders/checkout_success
    fail_redirect_url: https://www.germanyinthebox.com/orders/checkout_fail
