defaults: &defaults

  demo:
    # CREDITCARD :
    creditcard: # needed in development and testing only (we use it for the samples as well)
      merchant_id: 9105bb4f-ae68-4768-9c3b-3eda968f57ea
      merchant_secret: d1efed51-4cb9-46a5-ba7b-0fdc87a66544
    # UNIONPAY :
    upop: # needed in development and testing only (we use it for the samples as well)
      merchant_id: dfc3a296-3faf-4a1d-a075-f72f1b67dd2a
      merchant_secret: 6cbfa34e-91a7-421a-8dde-069fc0f5e0b8

  elastic_api:
    # CREDIT CARD :
    creditcard:
      username: <%= ENV["wirecard_elastic_api_creditcard_username"] %>
      password: <%= ENV["wirecard_elastic_api_creditcard_password"] %>
      engine_url: https://api-test.wirecard.com/engine/rest/
    # UNIONPAY :
    upop:
      username: <%= ENV["wirecard_elastic_api_upop_username"] %>
      password: <%= ENV["wirecard_elastic_api_upop_password"] %>
      engine_url: https://sandbox-engine.thesolution.com/engine/rest/

  hpp:
    # CREDIT CARD :
    creditcard:
      hosted_payment_url: https://api-test.wirecard.com/engine/hpp/
      notification_url: http://wirecard.germanyintebox.ultrahook.com
      psp_name: wirecard

    # UNIONPAY :
    upop:
      hosted_payment_url: https://sandbox-engine.thesolution.com/engine/hpp/
      psp_name: demo

    # UNIVERSAL
    transaction_types:
      upop: debit
      creditcard: purchase
      default: purchase

    default_redirect_url: http://local.dev:3000/customer/checkout/success
    cancel_redirect_url: http://local.dev:3000/customer/checkout/cancel
    processing_redirect_url: http://local.dev:3000/customer/checkout/processing
    success_redirect_url : http://local.dev:3000/customer/checkout/success
    fail_redirect_url: http://local.dev:3000/customer/checkout/fail

  merchants:
    reseller_id: <%= ENV["wirecard_merchants_reseller_id"] %>
    package_id: <%= ENV["wirecard_merchants_package_id"] %>
    country: DEU
    signup: https://www.checkoutportal.de/de_DE/signup/
    status:
      - unactive
      - active
      - processing
      - documents_complete
      - declined
      - terminated

local:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

  hpp:
    creditcard:
      hosted_payment_url: https://api-test.wirecard.com/engine/hpp/
      psp_name: wirecard
      notification_url: https://www.germanyintheboxdev.com/api/webhook/wirecard/customer
    upop:
      hosted_payment_url: https://sandbox-engine.thesolution.com/engine/hpp/
      psp_name: demo

    # UNIVERSAL
    transaction_types:
      default: purchase
      upop: debit
      creditcard: purchase

    default_redirect_url: https://www.germanyintheboxdev.com/customer/checkout/success
    cancel_redirect_url: https://www.germanyintheboxdev.com/customer/checkout/cancel
    processing_redirect_url: https://www.germanyintheboxdev.com/customer/checkout/processing
    success_redirect_url : https://www.germanyintheboxdev.com/customer/checkout/success
    fail_redirect_url: https://www.germanyintheboxdev.com/customer/checkout/fail

production:
  <<: *defaults

  elastic_api:
    # CREDIT CARD :
    creditcard:
      username: <%= ENV["wirecard_elastic_api_creditcard_username"] %>
      password: <%= ENV["wirecard_elastic_api_creditcard_password"] %>
      engine_url: https://api.wirecard.com/engine/rest/

    # UNIONPAY :
    upop:
      username: <%= ENV["wirecard_elastic_api_upop_username"] %>
      password: <%= ENV["wirecard_elastic_api_upop_password"] %>
      engine_url: https://api.wirecard.com/engine/rest/


  hpp:

    # CREDIT CARD :
    creditcard:
      hosted_payment_url: https://api.wirecard.com/engine/hpp/
      notification_url: https://www.germanyinthebox.com/api/webhook/wirecard/customer
      psp_name: wirecard

    # UNIONPAY :
    upop:
      hosted_payment_url: https://api.wirecard.com/engine/hpp/
      notification_url: https://www.germanyinthebox.com/api/webhook/wirecard/customer
      psp_name: wirecard

    # UNIVERSAL
    transaction_types:
      upop: debit
      creditcard: purchase
      default: purchase

    default_redirect_url: https://www.germanyinthebox.com/customer/checkout/success
    cancel_redirect_url: https://www.germanyinthebox.com/customer/checkout/cancel
    processing_redirect_url: https://www.germanyinthebox.com/customer/checkout/processing
    success_redirect_url : https://www.germanyinthebox.com/customer/checkout/success
    fail_redirect_url: https://www.germanyinthebox.com/customer/checkout/fail
